name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run1
        run: STD_ID='${{ secrets.STD_ID1 }}' PASSWORD='${{ secrets.PASSWORD1 }}' python3 main.py
      - name: run2
        run: STD_ID='${{ secrets.STD_ID2 }}' PASSWORD='${{ secrets.PASSWORD2 }}' python3 main.py
      - name: run3
        run: STD_ID='${{ secrets.STD_ID3 }}' PASSWORD='${{ secrets.PASSWORD3 }}' python3 main.py
